version: "3"

services:
    postgres:
        image: postgres
        container_name: baseimages_postgres_1
        environment:
            - POSTGRES_PASSWORD=dockerpresentation
        ports:
            - "5432:5432"
        networks:
            - db
    pgAdmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=dockerpresentation@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "2090:80"
        networks:
            - db
    django:
        image: carro_django:0.0.0.5
        ports:
            - "8000:8000"
        networks:
            - db
        links:
            - postgres
        depends_on:
            - postgres
networks:
    db:
        driver: bridge 