# Generated by Django 2.0.6 on 2019-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('marca', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
