# Generated by Django 2.0.6 on 2019-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='preco',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(default=0),
        ),
    ]
